Repository pagopa/pagopa-receipt-pdf-generator, pull requests merged in 2023-12, with the labels that each got.

#95 [fix] Fixed integration tests with new status TO_REVIEW
  integration-test/src/features/receipt_pdf_datastore.feature
Labels: bug, skip, size/small

#97 [PRDP-261] Updated RetryReviewedPoisonMessages function
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_generator_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/exception/UnableToSaveException.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/ReceiptCosmosService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/ReceiptCosmosServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessagesTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/ReceiptCosmosServiceImplTest.java
Labels: enhancement, size/large, minor

#99 [fix] Fixed method to update receipt on CosmosDB
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/receipt_pdf_generator_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/ReceiptCosmosClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/ReceiptCosmosClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/ReceiptCosmosService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/ReceiptCosmosServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessagesTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/ReceiptCosmosServiceImplTest.java
Labels: patch, size/small

#105 [PRDP-292] Added cart.item.subject exception
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#106 chore: Re-formatting daily report
  .gitignore
  report/src/utils/report.js
Labels: size/small

#109 chore: Refine report with biz2
  report/src/config/.env.local
  report/src/utils/report.js
  report/src/utils/utils.js
Labels: size/small

#110 fix: Report
  .github/workflows/daily_report_receipt.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
Labels: size/small

#108 [PRDP-298] feat: relax checks on anonym debtor
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: minor, size/small

#111 fix: GenerateReceiptPdfServiceImpl
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
Labels: patch, size/small

#112 Fix relaxed debtor checks
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small
