Repository pagopa/pagopa-receipt-pdf-generator, pull requests merged in 2023-11, with the labels that each got.

#64 [PRDP-186] Implement AES encryption and PDV Tokenizer
  .github/workflows/integration_test.yml
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_generator_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  integration-test/src/step_definitions/receipts_queue_client.js
  performance-test/src/modules/common.js
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/PDVTokenizerClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/PDVTokenizerClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/ReceiptError.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/exception/Aes256Exception.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/exception/PDVTokenizerException.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/tokenizer/ErrorResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/tokenizer/InvalidParam.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/tokenizer/PiiResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/tokenizer/TokenResource.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/PDVTokenizerService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/PDVTokenizerServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/Aes256Utils.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueueTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessagesTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/client/impl/PDVTokenizerClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/PDVTokenizerServiceImplTest.java
Labels: enhancement, size/large, minor

#65 [fix] Cleaned logs from unencrypted bizEvent payload
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
Labels: patch, size/small

#67 [fix] Fixed tokenizer path in prod
  helm/values-prod.yaml
Labels: size/small

#69 [fix] Updated reason error codes
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/enumeration/ReasonErrorCode.java
Labels: size/small

#68 [PRDP-198] feat: Removed check on paymentInfo.remittanceInformation
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#73 fix: updated values-prod.yaml
  helm/values-prod.yaml
Labels: bug, skip, size/small

#74 [fix] Fixed payee.taxCode & payee.name mapping
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#75 [PRDP-211] Implement Regex for invalid names
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: size/small

#77 [PRDP-213] fix: Date parsing with daylight saving
  .github/workflows/code_review.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: bug, size/small

#78 [PRDP-212] fix: Authorization code
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#79 [PRDP-215] chore: Add service customer id
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/template/ReceiptPDFTemplate.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/template/Transaction.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/TemplateDataField.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: size/small

#80 [PRDP-224] Changed Remittance Information retrieve
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/BuildTemplateService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: size/small

#81 [PRDP-229] feat: updated fullName regexp
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: size/small

#82 [PRDP-225] feat: updated generated flag policy
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#88 [PRDP-214] Change RefNumber's value & type mapping
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small

#91 [PRDP-258] Added new Receipt status TO_REVIEW
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/receipt_pdf_generator_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/enumeration/ReceiptStatusType.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/ReceiptCosmosService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/ReceiptCosmosServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueueTest.java
Labels: patch

#92 fix: GHA report
  .github/workflows/daily_report_receipt.yml
  report/src/utils/report.js
Labels: size/small

#93 Update report.js
  report/src/utils/report.js
Labels: size/small
