Repository pagopa/pagopa-receipt-pdf-generator, pull requests merged in 2023-10, with the labels that each got.

#18 [PRDP-148] Removed fiscal code from pdf name
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/GenerateReceiptPdfService.java
Labels: patch, size/small

#6 [PRDP-130] feat: Add performance tests & pipeline
  .devops/performance-test-pipelines.yml
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/README.md
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/common.js
  performance-test/src/modules/datastore_client.js
  performance-test/src/modules/queue_client.js
  performance-test/src/receipt_generator.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/event/DebtorPosition.java
Labels: size/large

#19 [PRDP-104] feat: introducing cart data for notification in receipt
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/CartItem.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/EventData.java
Labels: patch, size/small

#20 fix: Upd mem req
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#23 [PRDP-70] Template mapping continuing develop
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/event/PaymentInfo.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/template/UserData.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
Labels: patch, size/small

#24 fix: Add missing field
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/EventData.java
Labels: bug, patch, size/small

#25 [PRDP-148] Reworked pdf name
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
Labels: patch, size/small

#28 [PRDP-70] fix: Update unit tests
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/CartItem.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/EventData.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/IOMessageData.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/ReasonError.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/ReceiptMetadata.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/PdfGeneration.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: size/large, patch

#32 [PRDP-154] fix: Opentelemetry loading issue
  agent/config.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: bug, minor, size/small

#30 [PRDP-153] fix: Update biz event and receipt in integration and performance tests
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_generator_step.js
  performance-test/src/modules/common.js
Labels: ignore-for-release

#37 [PRDP-161] feat: Improve temp file handling
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/PdfEngineClient.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/response/PdfEngineResponse.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/GenerateReceiptPdfService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/client/impl/PdfEngineClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: enhancement, patch

#36 [PRDP-168] feat: Format date value for template
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
Labels: enhancement, patch, size/small

#21 [PRDP-145] feat add logo management
  docker/docker-compose.yml
  helm/Chart.yaml
  helm/templates/configmaps.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/exception/PdfJsonMappingException.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/template/PSP.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: size/large, patch

#39 [PRDP-170] Changed value property for total in receipt
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
Labels: patch, size/small

#40 [PRDP-171] feat: Read PSP config from local file
  helm/templates/configmaps.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/exception/PdfJsonMappingException.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
  src/main/resources/psp_config_file.json
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
  src/test/resources/psp_config_file.json
Labels: size/large, patch

#41 [fix-currency-format] fix: Changed currency format
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/BizEventToPdfMapper.java
Labels: patch, size/small

#45 [PRDP-164] feat: Added specific section for payer error in receipt
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java
Labels: patch, size/small

#46 feat: add health check and updated helm chart values
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/Health.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/HealthTest.java
Labels: minor, size/small

#47 [PRDP-162] feat: Improve error message
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: minor, size/small

#51 fix: Deploy prod
  helm/values-prod.yaml
Labels: size/small

#52 [PRDP-176] chore: Update logs for alert
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
Labels: size/small

#56 [chore] Changed psp name mapping
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
  src/test/resources/psp_config_file.json
Labels: patch, size/small

#58 [PRDP-178] Added onboardingChannel info to template
  src/main/java/it/gov/pagopa/receipt/pdf/generator/model/template/Transaction.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: enhancement, patch, size/small

#59 [PRDP-180] feat: Avoid to retry receipt generation in case of missing property
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/exception/ReceiptGenerationNotToRetryException.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/GenerateReceiptPdfService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: enhancement, patch

#60 [PSP-182] chore: updated psp_config_file.json
  src/main/resources/psp_config_file.json
Labels: size/large, patch

#62 [PRDP-193] Migrate to java17
  .github/maven_code_review/action.yml
  .github/workflows/code_review.yml
  Dockerfile
  host.json
  pom.xml
Labels: minor, size/small
