Repository pagopa/pagopa-receipt-pdf-generator, pull requests merged in 2023-09, with the labels that each got.

#3 [fix] Updated app name in Chart.yaml
  helm/Chart.yaml
Labels: patch, size/small

#5 [fix] Added templates' zip
  src/main/resources/complete_template.zip
  src/main/resources/partial_template.zip
Labels: patch, size/small

#8 [PRDP-123] feat: Use deployment selfhosted runner for integration test
  .github/workflows/integration_test.yml
  integration-test/src/package.json
Labels: enhancement, skip, size/small

#7 [PRDP-133] fix: Change log service name
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/Info.java
  src/main/resources-filtered/application.properties
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/receipt/pdf/generator/InfoTest.java
  src/test/resources/META-INF/maven/it.gov.pagopa.receipt.pdf.datastore/receipt-pdf-datastore/pom.properties
Labels: bug, patch, size/small

#9 [PRDP-135] Added receipt's timestamps
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/GenerateReceiptPdfService.java
Labels: enhancement, minor, size/small

#10 [PRDP-137] fix: Move working directory to avoid host restart
  .env.example
  README.md
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/features/receipt_pdf_datastore.feature
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/PdfEngineClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/ReceiptBlobClientImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/client/impl/ReceiptQueueClientImpl.java
  src/main/resources/logback.xml
  src/test/java/it/gov/pagopa/receipt/pdf/generator/client/PdfEngineClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/client/ReceiptBlobClientImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/client/ReceiptQueueClientImplTest.java
Labels: bug, patch, size/small

#11 stub info
  src/main/java/it/gov/pagopa/receipt/pdf/generator/Info.java
Labels: size/small

#13 Rollback commented logs and info function
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/Info.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java
  src/test/resources/logback-test.xml
Labels: patch, size/small

#15 feat: Decrease max replica in UAT chart
  helm/values-uat.yaml
Labels: enhancement, skip, size/small
