Repository pagopa/pagopa-receipt-pdf-generator, pull requests merged in 2024-06, with the labels that each got.

#126 [PAGOPA-1830] fix-psp-data-iconto-and-bcc-calabria-nord
  src/main/resources/psp_config_file.json
Labels: patch, size/small

#127 feat: Self_hosted_runner_image_tag
  .github/workflows/deploy_with_github_runner.yml
Labels: patch

#128 chore: Fix bot report
  .github/workflows/daily_report_receipt.yml
Labels: skip

#129 feat: [PAGOPA-1882] receipt PDF Generation even in the absence of the payer's name and surname
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
Labels: patch, size/small
