Repository pagopa/pagopa-receipt-pdf-generator, pull requests merged in 2024-01, with the labels that each got.

#101 [PRDP-275] Implemented cart multi-item logic
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/BuildTemplateService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/GenerateReceiptPdfService.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImpl.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/ObjectMapperUtils.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/TemplateDataField.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImplTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/service/impl/GenerateReceiptPdfServiceImplTest.java
Labels: enhancement, size/large, minor

#102 [PRDP-279] Implemented cart logic ManageReceiptPoisonQueue function
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueueTest.java
Labels: enhancement, size/small

#103 [PRDP-280] Implemented cart logic RetryReviewedPoisonMessages function
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/utils/ReceiptUtils.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueueTest.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessagesTest.java
Labels: enhancement, size/small

#104 [PRDP-286] Added isCart field to Receipt
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/Receipt.java
Labels: enhancement, patch, size/small

#114 [PRDP-277] Updated integration test for cart implementation
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .gitignore
  .identity/00_data.tf
  .identity/03_github_environment.tf
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/receipt_pdf_datastore.feature
  integration-test/src/step_definitions/aesUtils.js
  integration-test/src/step_definitions/common.js
  integration-test/src/step_definitions/receipt_pdf_generator_step.js
  integration-test/src/step_definitions/receipts_datastore_client.js
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/service/impl/BuildTemplateServiceImpl.java
  src/test/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdfTest.java
Labels: size/large, skip

#115 [fix] Fixed aes env name for github env
  .github/workflows/code_review.yml
  .github/workflows/integration_test.yml
  .identity/03_github_environment.tf
Labels: skip, size/small

#117 chore: Script utils to rigenerate pdf rcv
  .gitignore
  regenerate/run.sh
  regenerate/src/README.md
  regenerate/src/config/.env.local.copy
  regenerate/src/package.json
  regenerate/src/utils/regenerate.js
  regenerate/src/utils/utils.js
  report/src/config/.env.local.copy
  report/src/utils/report.js
Labels: skip, size/small

#116 [PRDP-321] fix: Report
  report/src/utils/report.js
Labels: skip, size/small
