Repository pagopa/pagopa-receipt-pdf-generator, pull requests merged in 2024-08, with the labels that each got.

#131 [PAGOPA-2017] chore: Upgrade ExtensionBundle
  host.json
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/GenerateReceiptPdf.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/ManageReceiptPoisonQueue.java
  src/main/java/it/gov/pagopa/receipt/pdf/generator/RetryReviewedPoisonMessages.java
Labels: minor, size/small

#132 [PPANTT-98] feat: Update psp_config_file.json
  src/main/resources/psp_config_file.json
Labels: bug, patch, size/small

#133 [PAGOPA-2017] fix OutputBinding write
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/receipt/pdf/generator/entity/receipt/ReceiptError.java
Labels: size/small

#134 [PAGOPA-2017] fix: Update messageEncoding
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  host.json
  pom.xml
Labels: bug, size/small
